### ISSUE TITLE
NO HTTPS

### ISSUE THREAD

**Issue by csf30816** [ateesdalejr/ateesdalejr.github.io#1]
The link to the site is HTTPS secured but there is no HTTPS!! AHHHHHH!!!

**Comment by ateesdalejr** [comment]
Sorry. I've switched to a new domain provider and have yet to add the domain to cloudflare just yet. I should be able to get it working again soon.

**Comment by ateesdalejr** [comment]
Sweer! Fixed, 💃 HTTPS works as well as auto upgrade. (Cloud flare is awesome.)

**Comment by csf30816** [comment]
ikr
