### ISSUE TITLE
[Suggestion] Add a site favicon 

### ISSUE THREAD

**Issue by vutondesign** [ateesdalejr/ateesdalejr.github.io#3]
...my OCD made me make this issue.

**Comment by ateesdalejr** [comment]
Yeah that's probably a good idea. Just trying to think of what would make a good one is challenging. I'll come up with something good I think.

**Comment by vutondesign** [comment]
👍

**Comment by vutondesign** [comment]
I've followed you now, a lot of your stuff is really helpful.

**Comment by ateesdalejr** [comment]
@vutondesign Thanks for the follow. 👍 I try my best to make useful things I just have a really hard time staying focused on one subject for long periods of time because everything is all so very interesting.

**Comment by vutondesign** [comment]
@ateesdalejr No problem, and that's very relatable :P

**Comment by ateesdalejr** [comment]
@vutondesign 684257791602c361f67d58e26b80480e6d6d3d85 adds this.

**Comment by vutondesign** [comment]
Looks great!
